services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=thehackerlibrary
      - POSTGRES_USER=thehackerlibrary
      - POSTGRES_PASSWORD=thehackerlibrary
    ports:
      - "5432:5432"
    networks:
      custom_net:
        ipv4_address: 10.10.10.10

volumes:
  db_data: {}

networks:
  custom_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
          gateway: 10.10.10.1
